services:
  app:
    build:
      context: ./todo-app
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT:-9000}:${PORT:-9000}
    environment:
      APP_ENV: ${APP_ENV:-development}
      PORT: ${PORT:-9000}
      BLUEPRINT_DB_HOST: psql_bp
      BLUEPRINT_DB_PORT: 5432
      BLUEPRINT_DB_DATABASE: test_db
      BLUEPRINT_DB_USERNAME: test_user
      BLUEPRINT_DB_PASSWORD: test_password
      BLUEPRINT_DB_SCHEMA: public
    depends_on:
      psql_bp:
        condition: service_healthy
    networks:
      - blueprint

  frontend_dev:
    build:
      context: ./todo-app
      dockerfile: Dockerfile
      target: frontend_dev
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "3000:3000"
    volumes:
      - ./todo-app/frontend/src:/app/src
      - ./todo-app/frontend/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - blueprint

  frontend:
    build:
      context: ./todo-app
      dockerfile: Dockerfile
      target: frontend
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "5173:5173"
    networks:
      - blueprint

  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data
      - ./todo-app/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U test_user -d test_db || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - blueprint

volumes:
  psql_volume_bp:

networks:
  blueprint:

