name: Build and Test Todo-App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 4. Build and Start Services
      - name: Build and Start Services
        run: |
          cd todo-app
          docker-compose up -d --build

      # 5. Run Integration Tests (optional)
      - name: Run Integration Tests
        run: |
          echo "Add integration tests if needed."

      # 6. Stop Docker Compose Stack
      - name: Stop Docker Compose Stack
        run: |
          cd todo-app
          docker-compose down
